spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/warehouse
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  resources:
    add-mappings: true
server:
  port: 8080
